@if($errors->any())<div class="alert alert-danger">Please correct the highlighted role fields.</div>@endif
<div class="row g-4"><div class="col-xl-8">
    <div class="card content-card mb-4"><div class="card-header"><h2 class="h5 mb-1">Role details</h2></div><div class="card-body p-4"><div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="name">Name</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name',$role->name) }}" maxlength="255" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug',$role->slug) }}" maxlength="255" required @readonly($role->slug===\App\Models\Role::SUPER_ADMIN)><div class="form-text">Lowercase URL-style identifier, such as <code>content-editor</code>.</div>@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="3">{{ old('description',$role->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    </div></div></div>
    <div class="card content-card"><div class="card-header d-flex justify-content-between align-items-center"><div><h2 class="h5 mb-1">Permissions</h2><p class="small text-secondary mb-0">Choose the CMS actions this role can perform.</p></div></div><div class="card-body p-4">
        @forelse($permissionGroups as $module=>$permissions)<section class="border rounded p-3 mb-3" data-permission-group><div class="d-flex justify-content-between align-items-center mb-3"><h3 class="h6 mb-0">{{ $module }}</h3><button class="btn btn-sm btn-link text-decoration-none" type="button" data-select-group>Select all</button></div><div class="row g-2">@foreach($permissions as $permission)<div class="col-md-6"><div class="form-check"><input class="form-check-input" id="permission-{{ $permission->id }}" name="permissions[]" type="checkbox" value="{{ $permission->id }}" @checked(in_array($permission->id,old('permissions',$selectedPermissions)))><label class="form-check-label" for="permission-{{ $permission->id }}"><span class="d-block">{{ $permission->name }}</span><code class="small">{{ $permission->slug }}</code></label></div></div>@endforeach</div></section>@empty<p class="text-secondary mb-0">No active permissions are available.</p>@endforelse
        @error('permissions')<div class="text-danger small">{{ $message }}</div>@enderror @error('permissions.*')<div class="text-danger small">{{ $message }}</div>@enderror
    </div></div>
</div><div class="col-xl-4"><div class="card content-card sticky-xl-top" style="top:96px"><div class="card-header"><h2 class="h5 mb-0">Access status</h2></div><div class="card-body p-4"><input type="hidden" name="status" value="0"><div class="form-check form-switch"><input class="form-check-input" id="status" name="status" type="checkbox" value="1" @checked(old('status',$role->status??true)) @disabled($role->slug===\App\Models\Role::SUPER_ADMIN)><label class="form-check-label" for="status">Active role</label></div>@if($role->slug===\App\Models\Role::SUPER_ADMIN)<input type="hidden" name="status" value="1"><p class="small text-secondary mt-3 mb-0">Super Admin remains active and receives every active permission automatically.</p>@endif</div><div class="card-footer bg-white d-grid gap-2 py-3"><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button><a class="btn btn-light" href="{{ route('admin.roles.index') }}">Cancel</a></div></div></div></div>
@push('scripts')<script>document.querySelectorAll('[data-permission-group]').forEach(group=>{const button=group.querySelector('[data-select-group]'),boxes=[...group.querySelectorAll('input[type=checkbox]')];const sync=()=>button.textContent=boxes.length&&boxes.every(box=>box.checked)?'Clear all':'Select all';button?.addEventListener('click',()=>{const checked=!boxes.every(box=>box.checked);boxes.forEach(box=>box.checked=checked);sync();});boxes.forEach(box=>box.addEventListener('change',sync));sync();});</script>@endpush
