<div class="card content-card">
    <div class="card-header"><h2 class="h5 mb-1">Social link details</h2><p class="small text-secondary mb-0">Add a public social profile and optional icon class.</p></div>
    <div class="card-body p-4"><div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="platform">Platform <span class="text-danger">*</span></label><input class="form-control @error('platform') is-invalid @enderror" id="platform" name="platform" type="text" value="{{ old('platform', $footerSocialLink->platform) }}" maxlength="255" required>@error('platform')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="icon">Icon class</label><input class="form-control @error('icon') is-invalid @enderror" id="icon" name="icon" type="text" value="{{ old('icon', $footerSocialLink->icon) }}" maxlength="255" placeholder="bi bi-facebook">@error('icon')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="url">Profile URL <span class="text-danger">*</span></label><input class="form-control @error('url') is-invalid @enderror" id="url" name="url" type="url" value="{{ old('url', $footerSocialLink->url) }}" maxlength="2048" placeholder="https://example.com/profile" required>@error('url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="target">Open in</label><select class="form-select @error('target') is-invalid @enderror" id="target" name="target"><option value="_self" @selected(old('target', $footerSocialLink->target) === '_self')>Same tab</option><option value="_blank" @selected(old('target', $footerSocialLink->target) === '_blank')>New tab</option></select>@error('target')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="sort_order">Sort order</label><input class="form-control @error('sort_order') is-invalid @enderror" id="sort_order" name="sort_order" type="number" value="{{ old('sort_order', $footerSocialLink->sort_order ?? 0) }}" min="0" required>@error('sort_order')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><input name="status" type="hidden" value="0"><div class="form-check form-switch"><input class="form-check-input" id="status" name="status" type="checkbox" value="1" @checked(old('status', $footerSocialLink->status ?? true))><label class="form-check-label" for="status">Active</label></div></div>
    </div></div>
    <div class="card-footer bg-white d-flex justify-content-end gap-2 py-3"><a class="btn btn-light" href="{{ route('admin.website.footer.social.index') }}">Cancel</a><button class="btn btn-primary">{{ $submitLabel }}</button></div>
</div>
