@extends('layouts.admin')
@section('title', 'SEO Pages')
@section('page-title', 'SEO Pages')
@section('content')
    <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 mb-4"><div><h2 class="h5 mb-1">Page-wise SEO</h2><p class="text-secondary mb-0">Override global metadata for individual routes and content.</p></div><a class="btn btn-primary" href="{{ route('admin.website.seo.pages.create') }}">Add SEO page</a></div>
    <div class="card content-card">
        <div class="card-header"><form class="row g-2" method="GET" action="{{ route('admin.website.seo.pages.index') }}"><div class="col-sm-6 col-lg-5"><input class="form-control" name="search" type="search" value="{{ $search }}" placeholder="Search title, key, route, or meta title" aria-label="Search SEO pages"></div><div class="col-sm-4 col-lg-3"><select class="form-select" name="type" aria-label="Page type"><option value="">All types</option>@foreach (\App\Models\SeoPage::TYPES as $item)<option value="{{ $item }}" @selected($type === $item)>{{ \App\Models\Lead::label($item) }}</option>@endforeach</select></div><div class="col-auto"><button class="btn btn-outline-primary" type="submit">Filter</button></div>@if ($search !== '' || $type !== '')<div class="col-auto"><a class="btn btn-light" href="{{ route('admin.website.seo.pages.index') }}">Clear</a></div>@endif</form></div>
        <div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Page</th><th>Type</th><th>Route</th><th>Robots</th><th>Priority</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
            @forelse ($seoPages as $seoPage)<tr><td><div class="fw-semibold">{{ $seoPage->title ?: $seoPage->meta_title ?: $seoPage->page_key ?: 'Untitled SEO page' }}</div><div class="small text-secondary">{{ $seoPage->page_key ?: 'No page key' }}</div></td><td><span class="badge text-bg-light">{{ \App\Models\Lead::label($seoPage->page_type) }}</span></td><td><code>{{ $seoPage->route_path ?: 'Auto-resolved' }}</code></td><td><span class="badge {{ $seoPage->robots_index ? 'text-bg-success' : 'text-bg-danger' }}">{{ $seoPage->robots_index ? 'Index' : 'Noindex' }}</span> <span class="badge {{ $seoPage->robots_follow ? 'text-bg-info' : 'text-bg-secondary' }}">{{ $seoPage->robots_follow ? 'Follow' : 'Nofollow' }}</span></td><td>{{ $seoPage->priority }} <span class="small text-secondary">/ {{ $seoPage->change_frequency }}</span></td><td><form method="POST" action="{{ route('admin.website.seo.pages.toggle-status', $seoPage) }}">@csrf @method('PATCH')<button class="btn btn-sm {{ $seoPage->status ? 'btn-success' : 'btn-outline-secondary' }}" type="submit">{{ $seoPage->status ? 'Active' : 'Inactive' }}</button></form></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.website.seo.pages.edit', $seoPage) }}">Edit</a> <form class="d-inline" method="POST" action="{{ route('admin.website.seo.pages.destroy', $seoPage) }}" onsubmit="return confirm('Delete this SEO page?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Delete</button></form></td></tr>
            @empty<tr><td class="py-5 text-center text-secondary" colspan="7">{{ $search !== '' || $type !== '' ? 'No SEO pages match your filters.' : 'No page-specific SEO records yet. Global website SEO remains active.' }}</td></tr>@endforelse
        </tbody></table></div>@if ($seoPages->hasPages())<div class="card-footer py-3">{{ $seoPages->onEachSide(1)->links('pagination::bootstrap-5') }}</div>@endif
    </div>
@endsection
