@if ($errors->any())<div class="alert alert-danger"><strong>Please check the highlighted fields.</strong><ul class="mb-0 mt-2">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<div class="row g-4">
    <div class="col-xl-8">
        <div class="card content-card mb-4"><div class="card-header"><h2 class="h5 mb-1">1. Contact information</h2><p class="small text-secondary mb-0">Customer identity and the best ways to reach them.</p></div><div class="card-body p-4"><div class="row g-3">
            <div class="col-md-6"><label class="form-label" for="name">Name <span class="text-danger">*</span></label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $lead->name) }}" maxlength="255" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="company_name">Company</label><input class="form-control @error('company_name') is-invalid @enderror" id="company_name" name="company_name" value="{{ old('company_name', $lead->company_name) }}" maxlength="255">@error('company_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $lead->email) }}" maxlength="255">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="phone">Phone</label><input class="form-control @error('phone') is-invalid @enderror" id="phone" name="phone" value="{{ old('phone', $lead->phone) }}" maxlength="50">@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="whatsapp">WhatsApp</label><input class="form-control @error('whatsapp') is-invalid @enderror" id="whatsapp" name="whatsapp" value="{{ old('whatsapp', $lead->whatsapp) }}" maxlength="50">@error('whatsapp')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        </div></div></div>

        <div class="card content-card mb-4"><div class="card-header"><h2 class="h5 mb-1">2. Enquiry details</h2><p class="small text-secondary mb-0">What the customer needs and where the enquiry came from.</p></div><div class="card-body p-4"><div class="row g-3">
            <div class="col-md-6"><label class="form-label" for="subject">Subject</label><input class="form-control @error('subject') is-invalid @enderror" id="subject" name="subject" value="{{ old('subject', $lead->subject) }}" maxlength="255">@error('subject')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-6"><label class="form-label" for="service_id">Service</label><select class="form-select @error('service_id') is-invalid @enderror" id="service_id" name="service_id"><option value="">General enquiry</option>@foreach ($services as $service)<option value="{{ $service->id }}" @selected((string) old('service_id', $lead->service_id) === (string) $service->id)>{{ $service->title }}</option>@endforeach</select>@error('service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-12"><label class="form-label" for="message">Message</label><textarea class="form-control @error('message') is-invalid @enderror" id="message" name="message" rows="7">{{ old('message', $lead->message) }}</textarea>@error('message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="source">Source <span class="text-danger">*</span></label><select class="form-select @error('source') is-invalid @enderror" id="source" name="source" required>@foreach (\App\Models\Lead::SOURCES as $item)<option value="{{ $item }}" @selected(old('source', $lead->source) === $item)>{{ \App\Models\Lead::label($item) }}</option>@endforeach</select>@error('source')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="budget">Budget</label><input class="form-control @error('budget') is-invalid @enderror" id="budget" name="budget" value="{{ old('budget', $lead->budget) }}" maxlength="100" placeholder="e.g. ₹50,000 – ₹1,00,000">@error('budget')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="col-md-4"><label class="form-label" for="preferred_contact_method">Preferred contact</label><select class="form-select @error('preferred_contact_method') is-invalid @enderror" id="preferred_contact_method" name="preferred_contact_method"><option value="">Not specified</option>@foreach (\App\Models\Lead::CONTACT_METHODS as $item)<option value="{{ $item }}" @selected(old('preferred_contact_method', $lead->preferred_contact_method) === $item)>{{ ucfirst($item) }}</option>@endforeach</select>@error('preferred_contact_method')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        </div></div></div>
    </div>

    <div class="col-xl-4">
        <div class="card content-card sticky-xl-top" style="top: 96px;"><div class="card-header"><h2 class="h5 mb-1">3. Pipeline</h2><p class="small text-secondary mb-0">Ownership, priority, and next action.</p></div><div class="card-body p-4">
            <div class="mb-3"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach (\App\Models\Lead::STATUSES as $item)<option value="{{ $item }}" @selected(old('status', $lead->status) === $item)>{{ \App\Models\Lead::label($item) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="mb-3"><label class="form-label" for="priority">Priority</label><select class="form-select @error('priority') is-invalid @enderror" id="priority" name="priority" required>@foreach (\App\Models\Lead::PRIORITIES as $item)<option value="{{ $item }}" @selected(old('priority', $lead->priority) === $item)>{{ ucfirst($item) }}</option>@endforeach</select>@error('priority')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="mb-3"><label class="form-label" for="assigned_to">Assigned to</label><select class="form-select @error('assigned_to') is-invalid @enderror" id="assigned_to" name="assigned_to"><option value="">Unassigned</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) old('assigned_to', $lead->assigned_to) === (string) $user->id)>{{ $user->name }} ({{ $user->email }})</option>@endforeach</select>@error('assigned_to')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <div class="mb-4"><label class="form-label" for="follow_up_date">Follow-up date</label><input class="form-control @error('follow_up_date') is-invalid @enderror" id="follow_up_date" name="follow_up_date" type="datetime-local" value="{{ old('follow_up_date', $lead->follow_up_date?->format('Y-m-d\TH:i')) }}">@error('follow_up_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
            <input name="status_active" type="hidden" value="0"><div class="form-check form-switch"><input class="form-check-input" id="status_active" name="status_active" type="checkbox" value="1" @checked(old('status_active', $lead->status_active ?? true))><label class="form-check-label" for="status_active">Active lead</label></div>
        </div><div class="card-footer bg-white d-grid gap-2 py-3"><button class="btn btn-primary btn-lg" type="submit">{{ $submitLabel }}</button><a class="btn btn-light" href="{{ $lead->exists ? route('admin.leads.show', $lead) : route('admin.leads.index') }}">Cancel</a></div></div>
    </div>
</div>
