@extends('layouts.admin')

@section('title', 'Activity Logs')
@section('page-title', 'Activity Logs')

@section('content')
    @php
        $statusClasses=['success'=>'text-bg-success','failed'=>'text-bg-danger','warning'=>'text-bg-warning'];
        $actionClasses=['create'=>'text-bg-success','update'=>'text-bg-primary','settings'=>'text-bg-info','delete'=>'text-bg-danger','status'=>'text-bg-warning','backup'=>'text-bg-dark','login'=>'text-bg-success','logout'=>'text-bg-secondary','failed_login'=>'text-bg-danger'];
        $filtersActive=$search!==''||$module!==''||$action!==''||$status!==''||$dateFrom!==''||$dateTo!=='';
    @endphp
    <div class="d-flex justify-content-between align-items-start gap-3 mb-4"><div><h2 class="h5 mb-1">Admin audit trail</h2><p class="text-secondary mb-0">A read-only history of meaningful administrative and authentication activity.</p></div><span class="badge text-bg-dark">Read only</span></div>
    <div class="row g-3 mb-4">@foreach ([['Total activities',$summary['total'],'primary'],["Today's activities",$summary['today'],'info'],['Create actions',$summary['create'],'success'],['Update actions',$summary['update'],'primary'],['Delete actions',$summary['delete'],'danger'],['Failed activities',$summary['failed'],'warning']] as [$label,$value,$color])<div class="col-6 col-lg-4 col-xxl-2"><div class="card content-card h-100 border-start border-4 border-{{ $color }}"><div class="card-body"><div class="small text-secondary mb-1">{{ $label }}</div><div class="h3 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="card content-card"><div class="card-header"><form class="row g-2" method="GET"><div class="col-md-6 col-xl-4"><input class="form-control" name="search" type="search" value="{{ $search }}" placeholder="Search user, action, module, description, IP" aria-label="Search activity"></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="module"><option value="">All modules</option>@foreach($modules as $item)<option value="{{ $item }}" @selected($module===$item)>{{ \App\Models\ActivityLog::label($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="action"><option value="">All actions</option>@foreach($actions as $item)<option value="{{ $item }}" @selected($action===$item)>{{ \App\Models\ActivityLog::label($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(\App\Models\ActivityLog::STATUSES as $item)<option value="{{ $item }}" @selected($status===$item)>{{ ucfirst($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_from" type="date" value="{{ $dateFrom }}" aria-label="From date"></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_to" type="date" value="{{ $dateTo }}" aria-label="To date"></div><div class="col-auto"><button class="btn btn-outline-primary">Filter</button></div>@if($filtersActive)<div class="col-auto"><a class="btn btn-light" href="{{ route('admin.activity-logs.index') }}">Clear</a></div>@endif</form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>User</th><th>Action</th><th>Module</th><th>Description</th><th>Status</th><th>IP address</th><th>Date</th><th class="text-end">Action</th></tr></thead><tbody>
        @forelse($activityLogs as $log)<tr><td><div class="fw-semibold">{{ $log->user_name ?: 'System / Guest' }}</div><div class="small text-secondary">{{ $log->user_email ?: 'No email' }}</div></td><td><span class="badge {{ $actionClasses[$log->action] ?? 'text-bg-light' }}">{{ \App\Models\ActivityLog::label($log->action) }}</span></td><td><span class="badge text-bg-light">{{ \App\Models\ActivityLog::label($log->module) }}</span></td><td><div class="text-truncate" style="max-width:22rem">{{ $log->description ?: 'No description' }}</div>@if($log->model_type)<div class="small text-secondary">{{ class_basename($log->model_type) }}{{ $log->model_id ? ' #'.$log->model_id : '' }}</div>@endif</td><td><span class="badge {{ $statusClasses[$log->status] ?? 'text-bg-secondary' }}">{{ ucfirst($log->status) }}</span></td><td><code>{{ $log->ip_address ?: '—' }}</code></td><td class="text-nowrap">{{ $log->created_at?->format('d M Y') ?: '—' }}@if($log->created_at)<div class="small text-secondary">{{ $log->created_at->format('h:i:s A') }}</div>@endif</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.activity-logs.show',$log) }}">View details</a></td></tr>
        @empty<tr><td class="py-5 text-center text-secondary" colspan="8">{{ $filtersActive ? 'No activity logs match the selected filters.' : 'No administrative activity has been recorded yet.' }}</td></tr>@endforelse
    </tbody></table></div>@if($activityLogs->hasPages())<div class="card-footer py-3">{{ $activityLogs->onEachSide(1)->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection
