@extends('layouts.admin')

@section('title', 'Activity Details')
@section('page-title', 'Activity Details')

@section('content')
    @php
        $statusClasses=['success'=>'text-bg-success','failed'=>'text-bg-danger','warning'=>'text-bg-warning'];
        $actionClasses=['create'=>'text-bg-success','update'=>'text-bg-primary','settings'=>'text-bg-info','delete'=>'text-bg-danger','status'=>'text-bg-warning','backup'=>'text-bg-dark','login'=>'text-bg-success','logout'=>'text-bg-secondary','failed_login'=>'text-bg-danger'];
    @endphp
    <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('admin.activity-logs.index') }}">&larr; Activity logs</a><div class="d-flex flex-wrap gap-2 align-items-center mt-2"><h2 class="h4 mb-0">{{ \App\Models\ActivityLog::label($activityLog->action) }}</h2><span class="badge {{ $actionClasses[$activityLog->action] ?? 'text-bg-light' }}">{{ \App\Models\ActivityLog::label($activityLog->module) }}</span><span class="badge {{ $statusClasses[$activityLog->status] ?? 'text-bg-secondary' }}">{{ ucfirst($activityLog->status) }}</span></div><p class="text-secondary mb-0 mt-1">Activity #{{ $activityLog->id }} · {{ $activityLog->created_at?->format('d M Y, h:i:s A') ?: 'Unknown date' }}</p></div><span class="badge text-bg-dark">Read only</span></div>
    <div class="row g-4"><div class="col-xl-8"><div class="card content-card mb-4"><div class="card-header"><h3 class="h6 mb-0">Activity</h3></div><div class="card-body p-4"><div class="small text-secondary mb-1">Description</div><p class="mb-4">{{ $activityLog->description ?: 'No description was recorded.' }}</p><dl class="row mb-0"><dt class="col-sm-4 text-secondary fw-normal">Action</dt><dd class="col-sm-8">{{ \App\Models\ActivityLog::label($activityLog->action) }}</dd><dt class="col-sm-4 text-secondary fw-normal">Module</dt><dd class="col-sm-8">{{ \App\Models\ActivityLog::label($activityLog->module) }}</dd><dt class="col-sm-4 text-secondary fw-normal">Model</dt><dd class="col-sm-8">{{ $activityLog->model_type ? class_basename($activityLog->model_type) : 'Not applicable' }}</dd><dt class="col-sm-4 text-secondary fw-normal">Model ID</dt><dd class="col-sm-8 mb-0">{{ $activityLog->model_id ?: 'Not applicable' }}</dd></dl></div></div>
        <div class="row g-4">@foreach(['old_values'=>'Previous values','new_values'=>'New values'] as $field=>$label)<div class="col-lg-6"><div class="card content-card h-100"><div class="card-header"><h3 class="h6 mb-0">{{ $label }}</h3></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><tbody>@forelse(($activityLog->{$field} ?? []) as $key=>$value)<tr><th class="ps-3 text-secondary fw-normal" style="width:38%">{{ \App\Models\ActivityLog::label($key) }}</th><td class="pe-3 text-break">@if($value==='[REDACTED]')<span class="badge text-bg-dark">Redacted</span>@elseif(is_array($value))<pre class="small bg-light rounded p-2 mb-0">{{ json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) }}</pre>@elseif(is_bool($value)){{ $value?'True':'False' }}@elseif($value===null)<span class="text-secondary">Null</span>@else{{ $value }}@endif</td></tr>@empty<tr><td class="text-center text-secondary py-4">No values recorded.</td></tr>@endforelse</tbody></table></div></div></div>@endforeach</div>
    </div><div class="col-xl-4"><div class="card content-card mb-4"><div class="card-header"><h3 class="h6 mb-0">Administrator</h3></div><div class="card-body p-4"><dl class="mb-0"><dt class="small text-secondary fw-normal">Name</dt><dd class="mb-3">{{ $activityLog->user_name ?: 'System / Guest' }}</dd><dt class="small text-secondary fw-normal">Email</dt><dd class="mb-3">{{ $activityLog->user_email ?: 'Not recorded' }}</dd><dt class="small text-secondary fw-normal">User ID</dt><dd class="mb-0">{{ $activityLog->user_id ?: 'Not recorded' }}</dd></dl></div></div><div class="card content-card"><div class="card-header"><h3 class="h6 mb-0">Request context</h3></div><div class="card-body p-4"><dl class="mb-0"><dt class="small text-secondary fw-normal">IP address</dt><dd class="mb-3"><code>{{ $activityLog->ip_address ?: 'Not recorded' }}</code></dd><dt class="small text-secondary fw-normal">Method</dt><dd class="mb-3"><span class="badge text-bg-light">{{ $activityLog->method ?: 'N/A' }}</span></dd><dt class="small text-secondary fw-normal">URL</dt><dd class="small text-break mb-3">{{ $activityLog->url ?: 'Not recorded' }}</dd><dt class="small text-secondary fw-normal">User agent</dt><dd class="small text-break mb-0">{{ $activityLog->user_agent ?: 'Not recorded' }}</dd></dl></div></div></div></div>
@endsection
