@extends('layouts.admin')

@section('title', 'Newsletter Subscribers')
@section('page-title', 'Newsletter Subscribers')

@section('content')
    @php
        $statusClasses = ['subscribed' => 'text-bg-success', 'unsubscribed' => 'text-bg-secondary', 'pending' => 'text-bg-warning', 'blocked' => 'text-bg-danger'];
        $sourceClasses = ['footer' => 'text-bg-primary', 'popup' => 'text-bg-info', 'contact_page' => 'text-bg-dark', 'blog' => 'text-bg-warning', 'manual' => 'text-bg-secondary', 'api' => 'text-bg-success', 'other' => 'text-bg-light'];
        $filtersActive = $search !== '' || $source !== '' || $status !== '' || $dateFrom !== '' || $dateTo !== '';
    @endphp

    <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 mb-4">
        <div><h2 class="h5 mb-1">Email marketing audience</h2><p class="text-secondary mb-0">Manage newsletter consent, sources, and subscription activity.</p></div>
        <div class="d-flex gap-2"><a class="btn btn-outline-success" href="{{ route('admin.newsletter-subscribers.export', request()->query()) }}">Export CSV</a><a class="btn btn-primary" href="{{ route('admin.newsletter-subscribers.create') }}">Add subscriber</a></div>
    </div>

    <div class="row g-3 mb-4">
        @foreach ([['Total subscribers', $summary['total'], 'primary'], ['Subscribed', $summary['subscribed'], 'success'], ['Unsubscribed', $summary['unsubscribed'], 'secondary'], ['Pending', $summary['pending'], 'warning'], ['Blocked', $summary['blocked'], 'danger'], ["Today's subscribers", $summary['today'], 'info']] as [$label, $value, $color])
            <div class="col-6 col-lg-4 col-xxl-2"><div class="card content-card h-100 border-start border-4 border-{{ $color }}"><div class="card-body"><div class="small text-secondary mb-1">{{ $label }}</div><div class="h3 mb-0">{{ $value }}</div></div></div></div>
        @endforeach
    </div>

    <div class="card content-card">
        <div class="card-header"><form class="row g-2" method="GET" action="{{ route('admin.newsletter-subscribers.index') }}"><div class="col-md-6 col-xl-4"><input class="form-control" name="search" type="search" value="{{ $search }}" placeholder="Search name, email, phone, source, status" aria-label="Search subscribers"></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="source"><option value="">All sources</option>@foreach (\App\Models\NewsletterSubscriber::SOURCES as $item)<option value="{{ $item }}" @selected($source === $item)>{{ \App\Models\NewsletterSubscriber::label($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach (\App\Models\NewsletterSubscriber::STATUSES as $item)<option value="{{ $item }}" @selected($status === $item)>{{ ucfirst($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_from" type="date" value="{{ $dateFrom }}" aria-label="Created from"></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_to" type="date" value="{{ $dateTo }}" aria-label="Created to"></div><div class="col-auto"><button class="btn btn-outline-primary" type="submit">Filter</button></div>@if ($filtersActive)<div class="col-auto"><a class="btn btn-light" href="{{ route('admin.newsletter-subscribers.index') }}">Clear</a></div>@endif</form></div>

        <div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Subscriber</th><th>Source</th><th>Status</th><th>Subscribed</th><th>Unsubscribed</th><th>Activity</th><th class="text-end">Actions</th></tr></thead><tbody>
            @forelse ($subscribers as $subscriber)
                <tr class="{{ $subscriber->status_active ? '' : 'opacity-75' }}"><td><a class="fw-semibold text-decoration-none" href="{{ route('admin.newsletter-subscribers.show', $subscriber) }}">{{ $subscriber->name ?: 'Unnamed subscriber' }}</a><div class="small">{{ $subscriber->email }}</div>@if ($subscriber->phone)<div class="small text-secondary">{{ $subscriber->phone }}</div>@endif</td><td><span class="badge {{ $sourceClasses[$subscriber->source] ?? 'text-bg-light' }}">{{ \App\Models\NewsletterSubscriber::label($subscriber->source) }}</span></td><td><span class="badge {{ $statusClasses[$subscriber->status] ?? 'text-bg-secondary' }}">{{ ucfirst($subscriber->status) }}</span>@unless ($subscriber->status_active)<div class="small text-secondary mt-1">Inactive record</div>@endunless</td><td class="text-nowrap">{{ $subscriber->subscribed_at?->format('d M Y') ?: '—' }}@if ($subscriber->subscribed_at)<div class="small text-secondary">{{ $subscriber->subscribed_at->format('h:i A') }}</div>@endif</td><td class="text-nowrap">{{ $subscriber->unsubscribed_at?->format('d M Y') ?: '—' }}@if ($subscriber->unsubscribed_at)<div class="small text-secondary">{{ $subscriber->unsubscribed_at->format('h:i A') }}</div>@endif</td><td class="text-nowrap"><div>{{ $subscriber->created_at->format('d M Y') }}</div><div class="small text-secondary">{{ $subscriber->created_at->diffForHumans() }}</div></td><td class="text-end text-nowrap"><div class="btn-group"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.newsletter-subscribers.show', $subscriber) }}">View</a><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.newsletter-subscribers.edit', $subscriber) }}">Edit</a><button class="btn btn-sm btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false"><span class="visually-hidden">Status actions</span></button><ul class="dropdown-menu dropdown-menu-end">@foreach (['subscribed'=>'Mark subscribed','unsubscribed'=>'Mark unsubscribed','blocked'=>'Block'] as $newStatus=>$label)<li><form method="POST" action="{{ route('admin.newsletter-subscribers.status.update', $subscriber) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $newStatus }}"><button class="dropdown-item {{ $newStatus === 'blocked' ? 'text-danger' : '' }}" type="submit">{{ $label }}</button></form></li>@endforeach<li><hr class="dropdown-divider"></li><li><form method="POST" action="{{ route('admin.newsletter-subscribers.destroy', $subscriber) }}" onsubmit="return confirm('Delete this subscriber?')">@csrf @method('DELETE')<button class="dropdown-item text-danger" type="submit">Delete</button></form></li></ul></div></td></tr>
            @empty<tr><td class="py-5 text-center text-secondary" colspan="7">{{ $filtersActive ? 'No subscribers match the selected filters.' : 'No newsletter subscribers yet. Subscriptions will appear here.' }}</td></tr>@endforelse
        </tbody></table></div>@if ($subscribers->hasPages())<div class="card-footer py-3">{{ $subscribers->onEachSide(1)->links('pagination::bootstrap-5') }}</div>@endif
    </div>
@endsection
