@extends('layouts.admin')

@section('title', $newsletterSubscriber->email)
@section('page-title', 'Subscriber Details')

@section('content')
    @php $statusClasses = ['subscribed' => 'text-bg-success', 'unsubscribed' => 'text-bg-secondary', 'pending' => 'text-bg-warning', 'blocked' => 'text-bg-danger']; @endphp
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('admin.newsletter-subscribers.index') }}">&larr; Newsletter subscribers</a><div class="d-flex flex-wrap align-items-center gap-2 mt-2"><h2 class="h4 mb-0">{{ $newsletterSubscriber->name ?: $newsletterSubscriber->email }}</h2><span class="badge {{ $statusClasses[$newsletterSubscriber->status] ?? 'text-bg-secondary' }}">{{ ucfirst($newsletterSubscriber->status) }}</span>@unless($newsletterSubscriber->status_active)<span class="badge text-bg-dark">Inactive record</span>@endunless</div><p class="text-secondary mb-0 mt-1">Added {{ $newsletterSubscriber->created_at->format('d M Y, h:i A') }}</p></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary" href="mailto:{{ $newsletterSubscriber->email }}">Email</a><a class="btn btn-primary" href="{{ route('admin.newsletter-subscribers.edit', $newsletterSubscriber) }}">Edit</a><form method="POST" action="{{ route('admin.newsletter-subscribers.destroy', $newsletterSubscriber) }}" onsubmit="return confirm('Delete this subscriber?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Delete</button></form></div></div>

    <div class="row g-4"><div class="col-xl-8"><div class="card content-card mb-4"><div class="card-header"><h3 class="h6 mb-0">Contact and subscription details</h3></div><div class="card-body p-4"><div class="row g-4"><div class="col-md-6"><div class="small text-secondary">Name</div><div class="fw-semibold">{{ $newsletterSubscriber->name ?: 'Not provided' }}</div></div><div class="col-md-6"><div class="small text-secondary">Email</div><a href="mailto:{{ $newsletterSubscriber->email }}">{{ $newsletterSubscriber->email }}</a></div><div class="col-md-6"><div class="small text-secondary">Phone</div><div>{{ $newsletterSubscriber->phone ?: 'Not provided' }}</div></div><div class="col-md-6"><div class="small text-secondary">Source</div><div>{{ \App\Models\NewsletterSubscriber::label($newsletterSubscriber->source) }}</div></div><div class="col-md-6"><div class="small text-secondary">Subscribed at</div><div>{{ $newsletterSubscriber->subscribed_at?->format('d M Y, h:i A') ?: 'Not recorded' }}</div></div><div class="col-md-6"><div class="small text-secondary">Unsubscribed at</div><div>{{ $newsletterSubscriber->unsubscribed_at?->format('d M Y, h:i A') ?: 'Not recorded' }}</div></div></div></div></div><div class="card content-card"><div class="card-header"><h3 class="h6 mb-0">Internal notes</h3></div><div class="card-body p-4"><div class="{{ $newsletterSubscriber->notes ? '' : 'text-secondary' }}" style="white-space:pre-wrap">{{ $newsletterSubscriber->notes ?: 'No internal notes.' }}</div></div></div></div>
        <div class="col-xl-4"><div class="card content-card mb-4"><div class="card-header"><h3 class="h6 mb-0">Status actions</h3></div><div class="card-body p-4 d-grid gap-2">@foreach (['subscribed'=>['Mark subscribed','btn-outline-success'],'unsubscribed'=>['Mark unsubscribed','btn-outline-secondary'],'pending'=>['Mark pending','btn-outline-warning'],'blocked'=>['Block subscriber','btn-outline-danger']] as $newStatus=>[$label,$class])<form method="POST" action="{{ route('admin.newsletter-subscribers.status.update', $newsletterSubscriber) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $newStatus }}"><button class="btn {{ $class }} w-100" type="submit" @disabled($newsletterSubscriber->status === $newStatus)>{{ $label }}</button></form>@endforeach</div></div><div class="card content-card"><div class="card-header"><h3 class="h6 mb-0">Submission reference</h3></div><div class="card-body p-4"><dl class="mb-0"><dt class="small text-secondary fw-normal">IP address</dt><dd class="mb-3"><code>{{ $newsletterSubscriber->ip_address ?: 'Not recorded' }}</code></dd><dt class="small text-secondary fw-normal">User agent</dt><dd class="small text-break mb-3">{{ $newsletterSubscriber->user_agent ?: 'Not recorded' }}</dd><dt class="small text-secondary fw-normal">Unsubscribe token</dt><dd class="mb-0"><code class="small text-break">{{ $newsletterSubscriber->unsubscribe_token ?: 'Not generated' }}</code></dd></dl></div></div></div>
    </div>
@endsection
