@extends('layouts.admin')

@section('title', 'Backups')
@section('page-title', 'Backups')

@section('content')
    @php
        $statusClasses = ['pending'=>'text-bg-secondary','processing'=>'text-bg-info','completed'=>'text-bg-success','failed'=>'text-bg-danger'];
        $typeClasses = ['database'=>'text-bg-primary','files'=>'text-bg-info','full'=>'text-bg-dark','content_export'=>'text-bg-warning'];
        $filtersActive = $search !== '' || $type !== '' || $status !== '' || $dateFrom !== '' || $dateTo !== '';
        $storageSize = (new \App\Models\BackupRecord(['file_size' => $summary['storage']]))->formattedFileSize();
    @endphp
    <div class="alert alert-warning d-flex gap-2 align-items-start" role="alert"><span aria-hidden="true">⚠</span><div><strong>Backups contain sensitive website data.</strong> Download and store them securely. Backup files remain in private application storage and are available only through authenticated downloads.</div></div>
    <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 mb-4"><div><h2 class="h5 mb-1">Backup manager</h2><p class="text-secondary mb-0">Generate and securely manage database, uploads, full-site, and content archives.</p></div><a class="btn btn-primary" href="{{ route('admin.backups.create') }}">Generate backup</a></div>
    <div class="row g-3 mb-4">@foreach ([['Total backups',$summary['total'],'primary'],['Completed',$summary['completed'],'success'],['Failed',$summary['failed'],'danger'],['Database',$summary['database'],'info'],['Full backups',$summary['full'],'dark'],['Storage used',$storageSize,'warning']] as [$label,$value,$color])<div class="col-6 col-lg-4 col-xxl-2"><div class="card content-card h-100 border-start border-4 border-{{ $color }}"><div class="card-body"><div class="small text-secondary mb-1">{{ $label }}</div><div class="h3 mb-0">{{ $value }}</div></div></div></div>@endforeach</div>
    <div class="card content-card"><div class="card-header"><form class="row g-2" method="GET"><div class="col-md-6 col-xl-4"><input class="form-control" name="search" type="search" value="{{ $search }}" placeholder="Search name, file, type, or status" aria-label="Search backups"></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="type"><option value="">All types</option>@foreach (\App\Models\BackupRecord::TYPES as $item)<option value="{{ $item }}" @selected($type === $item)>{{ \App\Models\BackupRecord::label($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach (\App\Models\BackupRecord::STATUSES as $item)<option value="{{ $item }}" @selected($status === $item)>{{ ucfirst($item) }}</option>@endforeach</select></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_from" type="date" value="{{ $dateFrom }}" aria-label="Created from"></div><div class="col-6 col-md-3 col-xl-2"><input class="form-control" name="date_to" type="date" value="{{ $dateTo }}" aria-label="Created to"></div><div class="col-auto"><button class="btn btn-outline-primary">Filter</button></div>@if ($filtersActive)<div class="col-auto"><a class="btn btn-light" href="{{ route('admin.backups.index') }}">Clear</a></div>@endif</form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Backup</th><th>Type</th><th>Status</th><th>Size</th><th>Created</th><th>Completed</th><th>Created by</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse ($backups as $backup)<tr><td><a class="fw-semibold text-decoration-none" href="{{ route('admin.backups.show', $backup) }}">{{ $backup->name ?: \App\Models\BackupRecord::label($backup->type).' backup' }}</a><div class="small text-secondary text-break">{{ str_starts_with($backup->file_name, 'pending-') ? 'Archive not generated' : $backup->file_name }}</div></td><td><span class="badge {{ $typeClasses[$backup->type] ?? 'text-bg-light' }}">{{ \App\Models\BackupRecord::label($backup->type) }}</span></td><td><span class="badge {{ $statusClasses[$backup->status] ?? 'text-bg-secondary' }}">{{ ucfirst($backup->status) }}</span></td><td>{{ $backup->formattedFileSize() }}</td><td class="text-nowrap">{{ $backup->created_at->format('d M Y') }}<div class="small text-secondary">{{ $backup->created_at->format('h:i A') }}</div></td><td class="text-nowrap">{{ $backup->completed_at?->format('d M Y') ?: '—' }}@if($backup->completed_at)<div class="small text-secondary">{{ $backup->completed_at->format('h:i A') }}</div>@endif</td><td>{{ $backup->creator?->name ?: 'System' }}</td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.backups.show', $backup) }}">View</a> @if($backup->status === 'completed')<a class="btn btn-sm btn-outline-success" href="{{ route('admin.backups.download', $backup) }}">Download</a>@endif <form class="d-inline" method="POST" action="{{ route('admin.backups.destroy', $backup) }}" onsubmit="return confirm('Delete this backup record and its private archive?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>
        @empty<tr><td class="py-5 text-center text-secondary" colspan="8">{{ $filtersActive ? 'No backups match the selected filters.' : 'No backups have been generated yet.' }}</td></tr>@endforelse
    </tbody></table></div>@if($backups->hasPages())<div class="card-footer py-3">{{ $backups->onEachSide(1)->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection
