@extends('layouts.admin')
@section('title', $backup->name ?: 'Backup Details')
@section('page-title', 'Backup Details')
@section('content')
    @php $statusClasses=['pending'=>'text-bg-secondary','processing'=>'text-bg-info','completed'=>'text-bg-success','failed'=>'text-bg-danger']; @endphp
    <div class="d-flex flex-column flex-lg-row justify-content-between align-items-lg-center gap-3 mb-4"><div><a class="small text-decoration-none" href="{{ route('admin.backups.index') }}">&larr; Backups</a><div class="d-flex align-items-center flex-wrap gap-2 mt-2"><h2 class="h4 mb-0">{{ $backup->name ?: \App\Models\BackupRecord::label($backup->type).' backup' }}</h2><span class="badge {{ $statusClasses[$backup->status] ?? 'text-bg-secondary' }}">{{ ucfirst($backup->status) }}</span></div><p class="text-secondary mt-1 mb-0">Backup #{{ $backup->id }} · {{ \App\Models\BackupRecord::label($backup->type) }}</p></div><div class="d-flex gap-2">@if($backup->status === 'completed')<a class="btn btn-success" href="{{ route('admin.backups.download', $backup) }}">Download archive</a>@endif<form method="POST" action="{{ route('admin.backups.destroy', $backup) }}" onsubmit="return confirm('Delete this backup record and its private archive?')">@csrf @method('DELETE')<button class="btn btn-outline-danger">Delete</button></form></div></div>
    @if($backup->status === 'failed')<div class="alert alert-danger"><strong>Backup failed.</strong> {{ $backup->message }}</div>@elseif($backup->status === 'completed')<div class="alert alert-success">{{ $backup->message ?: 'Backup generated successfully.' }}</div>@else<div class="alert alert-info">{{ $backup->message ?: 'Backup is waiting to be processed.' }}</div>@endif
    <div class="row g-4"><div class="col-xl-8"><div class="card content-card"><div class="card-header"><h3 class="h6 mb-0">Archive information</h3></div><div class="card-body p-4"><dl class="row mb-0"><dt class="col-sm-4 text-secondary fw-normal">Type</dt><dd class="col-sm-8">{{ \App\Models\BackupRecord::label($backup->type) }}</dd><dt class="col-sm-4 text-secondary fw-normal">File name</dt><dd class="col-sm-8 text-break">{{ str_starts_with($backup->file_name, 'pending-') ? 'Not generated' : $backup->file_name }}</dd><dt class="col-sm-4 text-secondary fw-normal">Private disk</dt><dd class="col-sm-8"><code>{{ $backup->disk ?: 'local' }}</code></dd><dt class="col-sm-4 text-secondary fw-normal">File size</dt><dd class="col-sm-8">{{ $backup->formattedFileSize() }}</dd><dt class="col-sm-4 text-secondary fw-normal">Created</dt><dd class="col-sm-8">{{ $backup->created_at->format('d M Y, h:i A') }}</dd><dt class="col-sm-4 text-secondary fw-normal">Completed</dt><dd class="col-sm-8">{{ $backup->completed_at?->format('d M Y, h:i A') ?: 'Not completed' }}</dd><dt class="col-sm-4 text-secondary fw-normal">Created by</dt><dd class="col-sm-8 mb-0">{{ $backup->creator?->name ?: 'System' }}@if($backup->creator?->email)<div class="small text-secondary">{{ $backup->creator->email }}</div>@endif</dd></dl></div></div></div><div class="col-xl-4"><div class="card content-card"><div class="card-header"><h3 class="h6 mb-0">Security</h3></div><div class="card-body p-4"><p class="small text-secondary">This archive is stored under <code>storage/app/private/backups</code>. It has no direct public URL and download requires an authenticated record-bound route.</p><ul class="small mb-0"><li><code>.env</code> is never included.</li><li>Dependencies, logs, cache, and sessions are excluded.</li><li>Restore/import is not enabled.</li></ul></div></div></div></div>
@endsection
