<div class="card content-card">
    <div class="card-header"><h2 class="h5 mb-1">Link details</h2><p class="small text-secondary mb-0">Add an internal path or safe external destination.</p></div>
    <div class="card-body p-4"><div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="title">Title <span class="text-danger">*</span></label><input class="form-control @error('title') is-invalid @enderror" id="title" name="title" type="text" value="{{ old('title', $footerLink->title) }}" maxlength="255" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="footer_section_id">Footer section</label><select class="form-select @error('footer_section_id') is-invalid @enderror" id="footer_section_id" name="footer_section_id"><option value="">No section</option>@foreach ($sections as $section)<option value="{{ $section->id }}" @selected((int) old('footer_section_id', $footerLink->footer_section_id) === $section->id)>{{ $section->title }}</option>@endforeach</select>@error('footer_section_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><label class="form-label" for="url">URL <span class="text-danger">*</span></label><input class="form-control @error('url') is-invalid @enderror" id="url" name="url" type="text" value="{{ old('url', $footerLink->url) }}" maxlength="2048" placeholder="/about or https://example.com" required>@error('url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-5"><label class="form-label" for="icon">Icon class</label><input class="form-control @error('icon') is-invalid @enderror" id="icon" name="icon" type="text" value="{{ old('icon', $footerLink->icon) }}" maxlength="255" placeholder="bi bi-link-45deg">@error('icon')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-4"><label class="form-label" for="target">Open in</label><select class="form-select @error('target') is-invalid @enderror" id="target" name="target"><option value="_self" @selected(old('target', $footerLink->target) === '_self')>Same tab</option><option value="_blank" @selected(old('target', $footerLink->target) === '_blank')>New tab</option></select>@error('target')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-3"><label class="form-label" for="sort_order">Sort order</label><input class="form-control @error('sort_order') is-invalid @enderror" id="sort_order" name="sort_order" type="number" value="{{ old('sort_order', $footerLink->sort_order ?? 0) }}" min="0" required>@error('sort_order')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-12"><input name="status" type="hidden" value="0"><div class="form-check form-switch"><input class="form-check-input" id="status" name="status" type="checkbox" value="1" @checked(old('status', $footerLink->status ?? true))><label class="form-check-label" for="status">Active</label></div></div>
    </div></div>
    <div class="card-footer bg-white d-flex justify-content-end gap-2 py-3"><a class="btn btn-light" href="{{ route('admin.website.footer.links.index') }}">Cancel</a><button class="btn btn-primary" type="submit">{{ $submitLabel }}</button></div>
</div>
