@extends('layouts.admin')
@section('title','Permissions')
@section('page-title','Permissions')
@section('content')
<div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 mb-4"><div><h2 class="h5 mb-1">Permission catalogue</h2><p class="text-secondary mb-0">Define individual CMS capabilities and group them by module.</p></div><a class="btn btn-primary" href="{{ route('admin.permissions.create') }}">Create permission</a></div>
<div class="card content-card"><div class="card-header"><form class="row g-2" method="GET"><div class="col-md-5"><input class="form-control" name="search" type="search" value="{{ $search }}" placeholder="Search name, slug, or description"></div><div class="col-md-3"><select class="form-select" name="module"><option value="">All modules</option>@foreach($modules as $item)<option value="{{ $item }}" @selected($module===$item)>{{ $item }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option><option value="active" @selected($status==='active')>Active</option><option value="inactive" @selected($status==='inactive')>Inactive</option></select></div><div class="col-auto"><button class="btn btn-outline-primary" type="submit">Filter</button></div>@if($search!==''||$module!==''||$status!=='')<div class="col-auto"><a class="btn btn-light" href="{{ route('admin.permissions.index') }}">Clear</a></div>@endif</form></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Permission</th><th>Module</th><th>Roles</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($permissions as $permission)<tr><td><div class="fw-semibold">{{ $permission->name }}</div><code>{{ $permission->slug }}</code></td><td>{{ $permission->module?:'Other' }}</td><td>{{ $permission->roles_count }}</td><td><form method="POST" action="{{ route('admin.permissions.toggle-status',$permission) }}">@csrf @method('PATCH')<button class="btn btn-sm border-0 p-0" type="submit"><span class="badge {{ $permission->status?'text-bg-success':'text-bg-secondary' }}">{{ $permission->status?'Active':'Inactive' }}</span></button></form></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.permissions.edit',$permission) }}">Edit</a> <form class="d-inline" method="POST" action="{{ route('admin.permissions.destroy',$permission) }}" onsubmit="return confirm('Delete this permission?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" type="submit">Delete</button></form></td></tr>
@empty<tr><td class="py-5 text-center text-secondary" colspan="5">No permissions match the selected filters.</td></tr>@endforelse
</tbody></table></div>@if($permissions->hasPages())<div class="card-footer py-3">{{ $permissions->links('pagination::bootstrap-5') }}</div>@endif</div>
@endsection
